main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from store.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('webhook/stripe', stripe_webhook_view, name='stripe_webhook')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from store.views import IndexPageView, LessonsDetailView, OrderCreateView

app_name = 'store'

urlpatterns = [
    path('', IndexPageView.as_view(), name='store'),
    path('lessons/<int:pk>/', LessonsDetailView.as_view(), name='lessons'),
    path('order/<int:pk>/', OrderCreateView.as_view(), name='order'),
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserRegistrationView, UserLoginView, UserProfileView)

app_name = 'users'

urlpatterns = [
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile')

    ]

users/models.py
import uuid
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    STANDARD = 0
    LIGHT = 1
    OPTIMAL = 2
    FULL = 3
    STATUSES = (
        (STANDARD, 'Не оплачен'),
        (LIGHT, 'Лайт'),
        (OPTIMAL, 'Оптимальный'),
        (FULL, 'Полный'),
    )

    email = models.EmailField(blank=False, unique=True)
    is_verified_email = models.BooleanField(default=False)
    status = models.SmallIntegerField(default=STANDARD, choices=STATUSES)

    def save(self, *args, **kwargs):

        super(User, self).save(*args, **kwargs)
        expiration = now() + timedelta(hours=48)
        record = EmailVerification.objects.create(code=uuid.uuid4(), user=self, expiration=expiration)
        record.send_verification_email()


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()



    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Для подтверждения учетной записи {} перейдите по ссылке: {}'.format(
            self.user.username,
            verification_link
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from users.models import User


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'username1 form-control', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'username1 form-control', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'password1 form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'password1 form-control', 'placeholder': 'Повторите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'username1 form-control', 'placeholder': "Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'password1 form-control', 'placeholder': "Введите пароль"}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'username1 form-control',
        'readonly': True}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'username1 form-control',
        'readonly': True}))
    status = forms.ChoiceField(required=True, widget=forms.EmailInput(attrs={
        'class': 'username1 form-control',
        'readonly': True}))


    class Meta:
        model = User
        fields = ('username', 'email', 'status')

users/views.py
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView

from store.models import Lessons
from users.forms import UserRegistrationForm, UserLoginForm, UserProfileForm
from users.models import EmailVerification, User


class EmailVerificationView(TemplateView):
    title = 'Store - Подтверждение электронной почты'
    template_name = 'store/index.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('store:store'))


class UserRegistrationView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Вы успешно зарегестрировались! ' \
                      'На вашу почту было отправлено письмо для ' \
                      'подтверждения вашего email адресса'


class UserLoginView(LoginView):
    model = User
    form_class = UserLoginForm
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.request.user.pk,))


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'Store - Профиль'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserProfileView, self).get_context_data()
        context['lessons'] = Lessons.objects.all()

        return context

    def get(self, request, *args, **kwargs):
        if self.request.user.pk != self.kwargs['pk']:
            return HttpResponseRedirect(reverse('store:store'))
        else:
            return super().get(request, *args, **kwargs)

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Squadfree Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href=href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Squadfree - v4.11.0
  * Template URL: https://bootstrapmade.com/squadfree-free-bootstrap-template-creative/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-transparent-users">
    <div class="container d-flex align-items-center justify-content-between position-relative">

      <div class="logo">
        <img src="{% static 'img/BARBER LESSONS.png' %}" class="img-fluid" alt="">
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'store:store' %}">На главную</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

{% block content %}    {% endblock %}



  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
    <section id="hero">
        <main id="main">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="billing-details1">
                            <div class="form-wrapper">
                                <h3>Вход</h3>
                                {% if messages or form.non_field_errors %}
                                    <div id="errors">
                                        <div class="errors1">
                                            {% if messages %}
                                                {% for message in messages %}
                                                    {{ message }}
                                                {% endfor %}
                                            {% endif %}
                                            {% for error in form.non_field_errors %}
                                                {{ error }}
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                                <div class="form-container">
                                    <form action="{% url 'users:login' %}" method="POST">
                                        {% csrf_token %}
                                        {{ form.username }}
                                        {{ form.password }}
                                        <input class="btn login" type="submit" value="Войти"/>
                                        <p>Еше нет аккаунта? <a href="{% url 'users:registration' %}">Зарегестрироваться</a></p>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main><!-- End #main -->
    </section>
{% endblock content %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}


    <!-- ======= Hero Section ======= -->


    <main id="main">
    <input type="checkbox"  id="nav-toggle" hidden>
        <nav class="nav">
    <label for="nav-toggle" class="nav-toggle" onclick >Меню уроков </label>
        <h2 class="logo">
            <a href=""></a>
        </h2>
        <ul>
            {% for lesson in lessons %}
            <li><a href="{% url 'store:lessons' lesson.pk %}">{{lesson.name}}</a>
            {% endfor %}
        </ul>
    <div class="mask-content"></div>
        </nav>
        <section id="services" class="services">
            <div class="container">

                <div class="section-title" data-aos="fade-in" data-aos-delay="0">
                    <h2>Мой профиль:</h2>
                </div>
                <div class="row">
                    <div class="row d-flex justify-content-center align-items-center">
                    <div class="col-md-6 col-lg-4 ">
                        <div class="icon-box2" data-aos="fade-up">
                            {% if user.status > 0 %}
                                <input type="checkbox"  id="nav-toggle" hidden>

                                <label for="nav-toggle" class="btn login1" onclick >Начать учится! </label>

                            {% else %}
                            <div class="icon"><i class="bx bx-cart-add"></i></div>
                            <h4 class="title"><a href="">Приобрести доступ:</a></h4>
                            <p><input type="checkbox" id="c1" name="cc" />
                            <label for="c1"><span></span>Пакет "Лайт"  Цена: 5000Р</label></p>
                             <p><input type="checkbox" id="c1" name="cc" />
                            <label for="c1"><span></span>2 тариф Цена: 10000Р</label></p>
                           <p> <input type="checkbox" id="c1" name="cc" />
                            <label for="c1"><span></span>3 тариф Цена :15000Р</label></p>
                            <p><a href="{% url 'store:store' %}#price">Подробнее о тарифах</a></p>
                            <p><input class="btn login" type="submit" value="Перейти к оплате"/></p>
                            {% endif %}
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-4 ">
                        <div class="icon-box2" data-aos="fade-up" data-aos-delay="200">
                            <div class="icon"><i class="bx bxs-user-account"></i></div>
                            <h4 class="title"><a href="">Данные аккаунта</a></h4>
                            <p class="description"> Имя пользователя: {{ form.username }}</p>
                            <p class="description"> Email: {{ form.email }}</p>
                            <p><a href="#">Изменить пароль</a></p>
                        </div>
                    </div>


                </div>
</div>
            </div>
        </section>

        <!-- ======= Team Section ======= -->




    </main><!-- End #main -->



{% endblock content %}

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
    <section id="hero">
        <main id="main">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="billing-details1">
                            <div class="form-wrapper">
                                <h3>Регистрация</h3>
                                {% if form.errors %}
                                    <div id="errors">
                                        <div class="errors1">
                                            {% for error in form.password2.errors %}
                                                {{ error }}
                                            {% endfor %}
                                            {% for error in form.username.errors %}
                                                {{ error }}
                                            {% endfor %}
                                            {% for error in form.email.errors %}
                                                {{ error }}
                                            {% endfor %}

                                        </div>
                                    </div>
                                {% endif %}
                                <div class="form-container">
                                    <form action="{% url 'users:registration' %}" method="POST">
                                        {% csrf_token %}
                                        {{ form.username }}
                                        {{ form.email }}
                                        {{ form.password1 }}
                                        {{ form.password2 }}
                                        <input class="btn login" type="submit" value="Зарегестрироваться"/>
                                        <p>Уже есть аккунт? <a href="{% url 'users:login' %}">Войти</a></p>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main><!-- End #main -->
    </section>
{% endblock content %}